import type { FileCollection } from '../FileCollection.js';
import type { SourceItem } from '../SourceItem.js';

export const CURRENT_IUM_VERSION = 1;

export interface ToIumIndexV1 {
  version?: 1;
  options: FileCollection['options'];
  sources: SourceItem[];
}

/**
 * Index schema generated by the actual version of this package
 */
export type ToIumIndex = ToIumIndexV1;

/**
 * Union of all index schema versions, used internally to check and migrate the index for proper unserialization.
 */
export type ToIumIndexVersions = ToIumIndexV1;
