name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nodejs:
    uses: zakodium/workflows/.github/workflows/nodejs.yml@nodejs-v1
    with:
      lint-check-types: true
      npm-test-command: |
        if [[ "$(node --version)" == "v25."* ]]; then
          NODE_OPTIONS="--no-webstorage" node --run test-only
        else
          node --run test-only
        fi
